[project]
name = "car-price-prediction"
version = "0.1.0"
description = "Car price prediction service with BentoML"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy",
    "pandas",
    "ipykernel",
    "polars",
    "scikit-learn",
    "pyarrow",
    "category-encoders",
    "joblib",
    "bentoml>=1.1.0",
    "pytest",
    "flake8",
]
